books/urls.py
from django.urls import path
from books.views import book_views, api_views

app_name = 'books'

urlpatterns = [
    path('', book_views.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>', book_views.BookDetailView.as_view(), name='book_detail'),
    path('book/new/', book_views.BookCreateView.as_view(), name='book_new'),
    path('book/<int:pk>/edit/', book_views.BookUpdateView.as_view(), name='book_update'),
    path('book/<int:pk>/remove/', book_views.BookDeleteView.as_view(), name='book_delete'),
    path('api/book-list/', api_views.BookList.as_view(), name='api_book_list'),
    path('api/import-book/', api_views.ImportBookView.as_view(), name='api_book_import'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
]

books/models.py
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator
from isbn_field import ISBNField
# Create your models here.

# TODO -> create an author model since one book can have multiple authors, use many to many relationship


class Book(models.Model):
    title = models.CharField('Title', max_length=200, validators=[MinLengthValidator(2)])
    author = models.CharField('Author', max_length=100, validators=[MinLengthValidator(2)])
    pub_date = models.DateField('Publication Date')
    isbn_num = ISBNField('ISBN')
    page_count = models.IntegerField('Number of Pages', validators=[MinValueValidator(1)], blank=True, null=True)
    language = models.CharField('Language', max_length=4, validators=[MinLengthValidator(2)])
    preview_link = models.URLField('Preview')

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from books.models import Book


class BookForm(forms.ModelForm):
    isbn_num = forms.CharField(
        label="ISBN:",
        widget=forms.widgets.TextInput(attrs={
            'class': 'form-control form-input'}
        )
    )

    pub_date = forms.DateField(
        label='Publication Date',
        widget=forms.widgets.DateInput(attrs={
            'type': 'date',
            'class': 'form-control form-input'}
        )
    )

    def clean_language(self):
        lang = self.cleaned_data['language']
        if lang:
            if any(n.isdigit() for n in lang):
                raise forms.ValidationError('This field cannot contain numbers.')

            return lang

    class Meta:
        model = Book
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-input'}),
            'author': forms.TextInput(attrs={'class': 'form-control form-input'}),
            'page_count': forms.NumberInput(attrs={'class': 'form-control form-input'}),
            'preview_link': forms.TextInput(attrs={'class': 'form-control form-input'}),
            'language': forms.TextInput(attrs={'class': 'form-control form-input'}),
        }


class SearchBookForm(forms.Form):
    book_name = forms.CharField(
        label='Name', widget=forms.widgets.TextInput(attrs={'class': 'form-control form-input'}))
    keyword = forms.CharField(
        label='Keyword', widget=forms.widgets.TextInput(attrs={'class': 'form-control form-input'}))


class ImportConfirmForm(forms.Form):
    check_box = forms.BooleanField(
        required=False,
        label="Import?",
        widget=forms.CheckboxInput(attrs={
            'onchange': 'checkbox.ifChecked(this);',
            'class': 'form-check-input',
        }))

books/views/api_views.py
from rest_framework.generics import ListAPIView
from django_filters.rest_framework import DjangoFilterBackend
from books.api.serializers import BookSerializer
from django.views.generic import View, ListView
from django.core import serializers
from books.models import Book
from books.forms import SearchBookForm, ImportConfirmForm
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
import requests
import json
from . import API_URL
import pandas as pd
from myproject.settings import env


class BookList(ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_backends = (DjangoFilterBackend,)
    filterset_fields = {
        'title': ['icontains'],
        'author': ['icontains'],
        'language': ['icontains'],
        'pub_date': ['gte', 'lte'],
    }


class ImportBookView(View):
    form_class = SearchBookForm
    template_name = 'books/book_import.html'

    def set_search_session_data(self, request, data):
        for key, value in data.items():
            request.session[key] = value
        request.session.modified = True

    def set_book_session_data(self, request, books):
        request.session['books'] = serializers.serialize('json', books)

    def correct_date(self, pub_date):
        return pd.to_datetime(pub_date)

    def correct_isbn(self, book):
        return list(filter(
            lambda k: k['type'] != 'ISBN_10', book['volumeInfo'].get('industryIdentifiers'))
        )

    def search(self, name, value, term):
        api_key = env('API_KEY')
        params = f'q={name}+{term}:{value}&key={api_key}'  # TODO -> rewrite this hardcoded url
        books = requests.get(API_URL, params=params)
        books_json = books.json()
        return books_json.get('items')

    def get_books(self, books_json):  # TODO -> add try and except for weird book names
        book_list = []
        for book in books_json:
            pub_date = self.correct_date(book['volumeInfo'].get('publishedDate'))
            author = book['volumeInfo'].get('authors')[-1]  # TODO -> add author model and fix this
            isbn, = self.correct_isbn(book)

            book = Book(
                title=book['volumeInfo'].get('title'),
                author=author,
                pub_date=pub_date,
                isbn_num=isbn['identifier'],
                page_count=book['volumeInfo'].get('pageCount'),
                preview_link=book['volumeInfo'].get('previewLink'),
                language=book['volumeInfo'].get('language')
            )
            book_list.append(book)
        return book_list

    def add_books(self, books):
        for book in books:
            book.save()

    def is_already_created(self, isbn):
        try:
            created_books = Book.objects.values_list('isbn_num')[0]
        except IndexError:
            return False

        if isbn in created_books:
            return True
        return False

    def is_already_added(self, books, isbn):
        for book in books:
            if book.isbn_num == isbn:
                return True
        return False

    def get_checked_books(self, data, books):
        checked_books = []
        for isbn, action in data.items():
            for book in json.loads(books):
                book['fields']['pub_date'] = self.correct_date(book['fields']['pub_date'])
                book = Book(**book['fields'])
                if book.isbn_num == isbn \
                        and action == 'added' \
                        and not self.is_already_added(checked_books, isbn) \
                        and not self.is_already_created(isbn):
                    checked_books.append(book)
        return checked_books

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET)
        checkbox = ImportConfirmForm(request.GET)
        return render(request, self.template_name, {'form': form, 'checkbox': checkbox})

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)

        if 'searchSubmit' == data.get('submitBtn'):
            book_name = data.get('book_name')
            keyword = data.get('keyword')
            term = data.get('dropdown')

            books_json = self.search(book_name, keyword, term)
            book_list = self.get_books(books_json)

            self.set_book_session_data(request, book_list)

            response = serializers.serialize('json', book_list)
            return JsonResponse(response, safe=False)

        else:
            data = json.loads(request.body)
            book_list = request.session.get('books')

            checked_books = self.get_checked_books(data, book_list)
            self.add_books(checked_books)
            return JsonResponse('OK', safe=False)  # add redirecting

books/views/book_views.py
from django.urls import reverse_lazy
from books.models import Book
from books.forms import BookForm
from books.filters import BookFilter
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView)


# Create your views here.


class BookListView(ListView):
    model = Book
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        return context


class BookDetailView(DetailView):
    model = Book


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books:book_list')


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books:book_list')


class BookDeleteView(DeleteView):
    fields = '__all__'
    model = Book
    success_url = reverse_lazy('books:book_list')

books/templates/books/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Book Management System</title>
</head>
<body>
    {% include 'books/navbar.html' %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    {% block javascript %}

    {% endblock javascript %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

books/templates/books/book_confirm_delete.html
{% extends 'books/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p class="delete">Are you sure you want to delete <b>{{ object }}?</b></p>
        <input class="btn btn-danger" type="submit" value="Delete">
        <a class="btn btn-warning" href="{% url 'books:book_detail' pk=book.pk %}">Cancel</a>
    </form>
{% endblock content %}

books/templates/books/book_data.html
<p class="title">Title: {{ book.title }}</p>
<p>Author: {{ book.author }}</p>
<p>ISBN: {{ book.isbn_num }}</p>
<p>Language: {{ book.language }}</p>
<p>{{book.page_count }} pages</p>
<p><a href="{{ book.preview_link }}" target="_blank">Preview</a></p>
<p>Publication Date: {{ book.pub_date|date:"d/m/Y" }}r.</p>

books/templates/books/book_detail.html
{% extends 'books/base.html' %}
{% block content %}
    <div class="book-form">
        <h1>{{ book.title }}</h1>
        <h5>{{ book.author }} | Publicated on {{ book.pub_date }}</h5>
        <h5>ISBN: {{ book.isbn_num }}</h5>
        <h5>Language: {{ book.language }}</h5>
        <h5>{{ book.page_count }} pages.</h5>
        <h5><a href="{{ book.preview_link }}">Preview</a></h5>
        <a class="btn btn-primary" href="{% url 'books:book_update' pk=book.pk %}">Update</a>
        <a class="btn btn-danger" href="{% url 'books:book_delete' pk=book.pk%}">Delete</a>
    </div>
{% endblock content %}

books/templates/books/book_form.html
{% extends 'books/base.html' %}
{% block content %}
    <form method="POST" novalidate>
        {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p>{{ field.label_tag }} <span class="error">{{ error }}</span></p>
            {% endfor %}
        {% endfor %}
        {% endif %}

        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <h5>{{ field.label_tag }}</h5>
                {{ field }}
            </div>
        {% endfor %}
        <div class="form-group">
            {% if object %}
                <input class="btn btn-light" type="submit" value="Update">
            {% else %}
                <input class="btn btn-light" type="submit" value="Create">
            {% endif %}
        </div>
    </form>
{% endblock content %}

books/templates/books/book_import.html
{% extends 'books/base.html' %}
{% load bootstrap %}
{% load static %}
{% block content %}
    <form method="POST" class="form-inline" id="ImportForm">
        {% csrf_token %}
        <div class="form-group import-form">
            <h4>Search: </h4>
            {% for field in form.visible_fields %}
                <span>{{ field.label }}{{ field }}</span>
            {% endfor %}
        </div>
        <div class="import-form">
            <select name="dropdown" id="keywordDropdown" class="btn btn-light">
                <option value="intitle">Title</option>
                <option value="inauthor">Author</option>
                <option value="inpublisher">Publisher</option>
                <option value="subject">Subject</option>
                <option value="isbn">ISBN</option>
                <option value="lccn">LCCN</option>
                <option value="oclc">OCLC</option>
            </select>
        </div>
        <div class="form-group import-btn">
            <button name="searchSubmit" type="submit" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
                Search
            </button>
        </div>
    </form>

    {% include 'books/import_modal.html' %}

    <script type="text/javascript">
        var importForm = document.getElementById('ImportForm');

        importForm.addEventListener('submit', function(e){
            e.preventDefault();

            const url = '/api/import-book/'
            const csrftoken = this.getElementsByTagName('input')[0].value;

            const book_name = this.getElementsByTagName('span')[0].lastChild.value;
            const keyword = this.getElementsByTagName('span')[1].lastChild.value;
            const select = document.getElementById('keywordDropdown')
            const dropdown = select.options[select.selectedIndex].value

            const data = {
                'book_name': book_name,
                'keyword': keyword,
                'dropdown': dropdown,
                'submitBtn': 'searchSubmit',
            }

            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify(data),
            })
            .then(res => res.json())
            .then(data => {
                let books = JSON.parse(data);

                for (let book of books){
                    let modalBlock = document.getElementById('modalForm');
                    let bookFields = book['fields'];
                    let formattedDate = new Date(bookFields.pub_date).toLocaleString('pl-PL',
                        {
                            'day': '2-digit',
                            'month': '2-digit',
                            'year': 'numeric',
                        })

                    modalBlock.insertAdjacentHTML('beforeend', `
                    <div class="col-sm-5 mt-5 book-list">
                        <p class="title">Title: ${bookFields.title}</p>
                        <p>Author: ${bookFields.author}</p>
                        <p>ISBN: ${bookFields.isbn_num}</p>
                        <p>Language: ${bookFields.language}</p>
                        <p>${bookFields.page_count} pages</p>
                        <p><a href="${bookFields.preview_link}" target="_blank">Preview</a></p>
                        <p>Publication Date: ${formattedDate}r.</p>
                        <div class="form-check form-switch">
                            <span data-book="${bookFields.isbn_num}" data-action="not-added">{{ checkbox }}</span>
                        </div>
                    </div>
                    `)
                }
            })
            .catch(console.log)
        })
    </script>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript" src="{% static 'js/import.js' %}"></script>
{% endblock javascript %}

books/templates/books/book_list.html
{% extends 'books/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="text-center">
        <form method="GET">
            {% csrf_token %}
            {{ filter.form|bootstrap }}
            <button type="submit" class=" btn btn-outline-light">Search</button>
        </form>
    </div>
    <div class="row justify-content-center">
        {% for book in filter.qs %}
            <div class="col-sm-5 mt-5 book-list">
                {% include 'books/book_data.html' %}
                <a class="btn btn-light edit-btn" href="{% url 'books:book_detail' pk=book.pk %}">Edit</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

books/templates/books/import_modal.html
<!-- Modal -->
<form method="POST" id="ImportFormConfirm">
    {% csrf_token %}
    <div class="modal fade" id="exampleModalCenter" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div style="width:100%; max-width:1820px; margin: auto;" class="modal-lg modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 style="color: black;" class="modal-title" id="exampleModalLongTitle">Select which books you want to import.</h5>
                    <button type="button" class="btn btn-dark close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="modalForm" class="row justify-content-center">
                        <!-- Space for JS inserting -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button name="modalSubmit" type="button" class="close btn btn-dark" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-dark">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>

books/templates/books/navbar.html
<nav class="nav navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand home" href="{% url 'books:book_list' %}">Book List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'books:book_new' %}">Add new book</a>
            <a class="nav-item nav-link" href="{% url 'books:api_book_import' %}">Import</a>
            <a class="nav-item nav-link" href="{% url 'books:api_book_list' %}">API View List</a>
        </div>
    </div>
</nav>